services:
  db_prod:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - appnet_prod

  api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_projet_prod
    depends_on:
      - db_prod
    ports:
      - "8001:8000"
    env_file:
      - .env.prod
    networks:
      - appnet_prod

volumes:
  postgres_data_prod:

networks:
  appnet_prod:
    driver: bridge