services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_projet
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: [ "/app/entrypoint.sh" ]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge
