services:
  db_dev:
    image: postgres:15
    container_name: postgres_dev
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - appnet_dev

  api_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_projet_dev
    depends_on:
      - db_dev
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - appnet_dev

volumes:
  postgres_data_dev:

networks:
  appnet_dev:
    driver: bridge
