"""initial migration

Revision ID: 001_initial
Revises: 
Create Date: 2024-12-17 10:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.Column('uri_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id_restaurant'),
    sa.UniqueConstraint('uri_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('style',
    sa.Column('id_style', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('style_value', sa.String(length=255), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_style'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('terminal',
    sa.Column('id_terminal', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_terminal'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminal')
    op.drop_table('style')
    op.drop_table('client')
    op.drop_table('restaurant')
    # ### end Alembic commands ###