"""update_client_table

Revision ID: 252f279f5a45
Revises: 41ced9ae8eeb
Create Date: 2025-10-13 14:20:57.476999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252f279f5a45'
down_revision: Union[str, Sequence[str], None] = '41ced9ae8eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'uuid',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('client', 'loyalty_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'loyalty_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('client', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
