"""Add favicon

Revision ID: 271a1f6ec9df
Revises: 2c55145fafec
Create Date: 2025-11-09 11:05:21.741210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271a1f6ec9df'
down_revision: Union[str, Sequence[str], None] = '2c55145fafec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('favicon', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'favicon')
    # ### end Alembic commands ###
