"""add_missing_columns

Revision ID: 2a80a661fd8b
Revises: 001_initial
Create Date: 2025-12-17 10:13:32.853314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a80a661fd8b'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('loyalty_code', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('otp_hash', sa.String(length=64), nullable=True))
    op.add_column('client', sa.Column('otp_hash_expiration', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('client', sa.Column('id_restaurant', sa.Integer(), nullable=False))
    op.alter_column('client', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('client_uuid_key'), 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['loyalty_code'])
    op.create_foreign_key(None, 'client', 'restaurant', ['id_restaurant'], ['id_restaurant'])
    op.drop_column('client', 'is_verified')
    op.drop_column('client', 'otp_expiry')
    op.drop_column('client', 'created_at')
    op.drop_column('client', 'otp_code')
    op.add_column('restaurant', sa.Column('favicon', sa.String(length=200), nullable=False))
    op.alter_column('restaurant', 'logo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('restaurant', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('restaurant_uuid_key'), 'restaurant', type_='unique')
    op.alter_column('style', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('style', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('style', 'style_value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('style_uuid_key'), 'style', type_='unique')
    op.alter_column('terminal', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('terminal_uuid_key'), 'terminal', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('terminal_uuid_key'), 'terminal', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('terminal', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('style_uuid_key'), 'style', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('style', 'style_value',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('style', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('style', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('restaurant_uuid_key'), 'restaurant', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('restaurant', 'logo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('restaurant', 'favicon')
    op.add_column('client', sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('otp_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint(op.f('client_uuid_key'), 'client', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('client', 'email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('client', 'uuid',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               nullable=False)
    op.drop_column('client', 'id_restaurant')
    op.drop_column('client', 'active')
    op.drop_column('client', 'otp_hash_expiration')
    op.drop_column('client', 'otp_hash')
    op.drop_column('client', 'loyalty_code')
    # ### end Alembic commands ###
