"""initial_schema

Revision ID: 2c55145fafec
Revises: 
Create Date: 2025-11-06 08:56:21.308910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c55145fafec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id_restaurant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_restaurant'),
    sa.UniqueConstraint('uri_name')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('loyalty_code', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=True),
    sa.Column('otp_hash_expiration', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('loyalty_code')
    )
    op.create_table('style',
    sa.Column('id_style', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('style_value', sa.String(length=100), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_style')
    )
    op.create_table('terminal',
    sa.Column('id_terminal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_terminal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminal')
    op.drop_table('style')
    op.drop_table('client')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
