"""add restaurant, style and terminal

Revision ID: 64f0dfe9921f
Revises: 252f279f5a45
Create Date: 2025-11-04 17:07:48.372137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f0dfe9921f'
down_revision: Union[str, Sequence[str], None] = '252f279f5a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id_restaurant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=100), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_restaurant'),
    sa.UniqueConstraint('uri_name')
    )
    op.create_table('style',
    sa.Column('id_style', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('style_value', sa.String(length=100), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_style')
    )
    op.create_table('terminal',
    sa.Column('id_terminal', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_restaurant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurant'], ['restaurant.id_restaurant'], ),
    sa.PrimaryKeyConstraint('id_terminal')
    )
    op.add_column('client', sa.Column('id_restaurant', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'restaurant', ['id_restaurant'], ['id_restaurant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'id_restaurant')
    op.drop_table('terminal')
    op.drop_table('style')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
