"""add_client_table_fixed

Revision ID: 87015e1e26ee
Revises: f20aef36cb25
Create Date: 2025-09-17 13:02:59.985935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87015e1e26ee'
down_revision: Union[str, Sequence[str], None] = 'f20aef36cb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('loyalty_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=True),
    sa.Column('otp_hash_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('loyalty_code'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
