"""add_active_field_to_client

Revision ID: b7968c9f31ac
Revises: 87015e1e26ee
Create Date: 2025-10-13 14:07:05.228412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7968c9f31ac'
down_revision: Union[str, Sequence[str], None] = '87015e1e26ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculs_id'), table_name='calculs')
    op.drop_table('calculs')
    op.add_column('client', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('client', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column('client', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('client', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('client_mail_key'), 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['email'])
    op.drop_column('client', 'name')
    op.drop_column('client', 'mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('mail', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint(op.f('client_mail_key'), 'client', ['mail'], postgresql_nulls_not_distinct=False)
    op.drop_column('client', 'active')
    op.drop_column('client', 'email')
    op.drop_column('client', 'last_name')
    op.drop_column('client', 'first_name')
    op.create_table('calculs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('resultat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('operande_1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('operande_2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('calculs_pkey'))
    )
    op.create_index(op.f('ix_calculs_id'), 'calculs', ['id'], unique=False)
    # ### end Alembic commands ###
