"""

Revision ID: e3b1ae9bce0a
Revises: f8513e5aa165
Create Date: 2025-07-28 11:24:43.998336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b1ae9bce0a'
down_revision: Union[str, Sequence[str], None] = 'f8513e5aa165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculs', sa.Column('operande_1', sa.Float(), nullable=False))
    op.add_column('calculs', sa.Column('operande_2', sa.Float(), nullable=False))
    op.drop_column('calculs', 'operande')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculs', sa.Column('operande', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('calculs', 'operande_2')
    op.drop_column('calculs', 'operande_1')
    # ### end Alembic commands ###
