"""create calcul table

Revision ID: f8513e5aa165
Revises: 
Create Date: 2025-07-28 11:19:25.274505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8513e5aa165'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operande', sa.Float(), nullable=False),
    sa.Column('operation', sa.String(length=1), nullable=False),
    sa.Column('resultat', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculs_id'), 'calculs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculs_id'), table_name='calculs')
    op.drop_table('calculs')
    # ### end Alembic commands ###
