name: CD Production (build & push)

on:
  push:
    branches: [ main ]

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Production image
        run: |
          DATE_TAG=$(date +'%Y%m%d-%H%M')
          IMAGE_NAME="pa-2025-2026"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$DATE_TAG \
                       -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest \
                       -f Dockerfile.prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$DATE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
